import builtins from "builtin-modules";
import esbuild from "esbuild";

const environment = process.env.NODE_ENV;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["source/main.js"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "esnext",
  logLevel: "info",
  sourcemap: false,
  treeShaking: true,
  outfile: "dist/main.js",
  minify: false,
  keepNames: true,
  charset: "utf8",
  plugins: [
    {
      name: "push-to-vault",
      setup(build) {
        build.onEnd(async () => {
          console.info("Generating manifest...");
          await import("./scripts/generate/manifest.js");
          console.info("Copying files into vault...");
          await import("./scripts/push.js");
        });
      },
    },
  ],
});

console.info("Building files...");

await context.rebuild();

if (environment !== "development") {
  process.exit(0);
}
